"""create project chapter paragraph tables

Revision ID: 0c6341089f8f
Revises: 
Create Date: 2026-06-05 16:09:04.918461

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '0c6341089f8f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=False),
    sa.Column('primary_conversation_id', sa.String(length=40), nullable=False),
    sa.Column('active_session_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('chapter_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('paragraph_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_id', name='uq_chapters_project_chapter_id')
    )
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('chapter_pk', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.String(length=40), nullable=False),
    sa.Column('paragraph_id', sa.String(length=60), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chapter_pk'], ['chapters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'paragraph_id', name='uq_paragraphs_project_paragraph_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paragraphs')
    op.drop_table('chapters')
    op.drop_table('projects')
    # ### end Alembic commands ###
