"""add required scene plan fields

Revision ID: 13dbe8063496
Revises: b900da1799f5
Create Date: 2026-06-05 20:38:30.449188

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '13dbe8063496'
down_revision: str | Sequence[str] | None = 'b900da1799f5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_plan_scenes', sa.Column('interior_exterior', sa.String(length=40), nullable=False, server_default='待定'))
    op.add_column('scene_plan_scenes', sa.Column('must_cover_plot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('scene_plan_scenes', sa.Column('must_keep_dialogue', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('scene_plan_scenes', sa.Column('must_keep_visual_elements', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('scene_plan_scenes', sa.Column('must_keep_foreshadowing', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.alter_column('scene_plan_scenes', 'interior_exterior', server_default=None)
    op.alter_column('scene_plan_scenes', 'must_cover_plot', server_default=None)
    op.alter_column('scene_plan_scenes', 'must_keep_dialogue', server_default=None)
    op.alter_column('scene_plan_scenes', 'must_keep_visual_elements', server_default=None)
    op.alter_column('scene_plan_scenes', 'must_keep_foreshadowing', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene_plan_scenes', 'must_keep_foreshadowing')
    op.drop_column('scene_plan_scenes', 'must_keep_visual_elements')
    op.drop_column('scene_plan_scenes', 'must_keep_dialogue')
    op.drop_column('scene_plan_scenes', 'must_cover_plot')
    op.drop_column('scene_plan_scenes', 'interior_exterior')
    # ### end Alembic commands ###
