"""create script generation tables

Revision ID: 6502dba8d996
Revises: 13dbe8063496
Create Date: 2026-06-05 20:50:54.211739

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '6502dba8d996'
down_revision: str | Sequence[str] | None = '13dbe8063496'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_versions',
    sa.Column('script_version_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('script_version_id'),
    sa.UniqueConstraint('project_id', 'status', name='uq_script_versions_project_status')
    )
    op.create_table('script_content_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_version_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('scene_id', sa.String(length=40), nullable=False),
    sa.Column('content_block_id', sa.String(length=60), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker', sa.String(length=200), nullable=True),
    sa.Column('source_evidence_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.script_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_version_id', 'content_block_id', name='uq_script_blocks_version_block_id')
    )
    op.create_table('script_scenes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('script_version_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('scene_id', sa.String(length=40), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_chapter_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.script_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_version_id', 'scene_id', name='uq_script_scenes_version_scene_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('script_scenes')
    op.drop_table('script_content_blocks')
    op.drop_table('script_versions')
    # ### end Alembic commands ###
