"""create export jobs table

Revision ID: bda0f715280e
Revises: e526205f6520
Create Date: 2026-06-05 22:50:48.785163

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = 'bda0f715280e'
down_revision: str | Sequence[str] | None = 'e526205f6520'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_jobs',
    sa.Column('export_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('script_version_id', sa.String(length=40), nullable=False),
    sa.Column('format', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.script_version_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('export_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_jobs')
    # ### end Alembic commands ###
