"""create style profile tables

Revision ID: d476da1604e5
Revises: ea6c064a87ce
Create Date: 2026-06-05 19:20:18.805829

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'd476da1604e5'
down_revision: str | Sequence[str] | None = 'ea6c064a87ce'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('script_type', sa.String(length=120), nullable=False),
    sa.Column('dialogue_density', sa.String(length=80), nullable=False),
    sa.Column('scene_length', sa.String(length=80), nullable=False),
    sa.Column('pacing', sa.String(length=80), nullable=False),
    sa.Column('character_voice', sa.Text(), nullable=False),
    sa.Column('conflict_design', sa.Text(), nullable=False),
    sa.Column('narration_ratio', sa.String(length=80), nullable=False),
    sa.Column('action_ratio', sa.String(length=80), nullable=False),
    sa.Column('transitions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('user_preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', name='uq_style_profiles_project_id')
    )
    op.create_table('style_reference_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'file_id', name='uq_style_reference_files_project_file_id')
    )
    op.create_table('style_sources',
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('builtin_style', sa.String(length=80), nullable=True),
    sa.Column('style_text', sa.Text(), nullable=True),
    sa.Column('reference_file_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('style_sources')
    op.drop_table('style_reference_files')
    op.drop_table('style_profiles')
    # ### end Alembic commands ###
