"""add script scene metadata

Revision ID: f3174dfc508d
Revises: 6502dba8d996
Create Date: 2026-06-05 20:56:44.874268

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f3174dfc508d'
down_revision: str | Sequence[str] | None = '6502dba8d996'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script_scenes', sa.Column('scene_info', sa.Text(), nullable=False, server_default=''))
    op.add_column('script_scenes', sa.Column('characters', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('script_scenes', sa.Column('scene_purpose', sa.Text(), nullable=False, server_default=''))
    op.add_column('script_scenes', sa.Column('core_conflict', sa.Text(), nullable=False, server_default=''))
    op.alter_column('script_scenes', 'scene_info', server_default=None)
    op.alter_column('script_scenes', 'characters', server_default=None)
    op.alter_column('script_scenes', 'scene_purpose', server_default=None)
    op.alter_column('script_scenes', 'core_conflict', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script_scenes', 'core_conflict')
    op.drop_column('script_scenes', 'scene_purpose')
    op.drop_column('script_scenes', 'characters')
    op.drop_column('script_scenes', 'scene_info')
    # ### end Alembic commands ###
